# Generated by Django 3.0.4 on 2021-05-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=40, verbose_name='Domicilio')),
                ('cp', models.IntegerField(verbose_name='Código Postal')),
                ('localidad', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=40)),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('codigoArea', models.IntegerField(verbose_name='Prefijo')),
                ('celular', models.IntegerField(verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('confirmacionEmail', models.EmailField(max_length=254, verbose_name='Repita Correo electrónico')),
                ('facebook', models.CharField(blank=True, max_length=40, null=True)),
                ('instagram', models.CharField(blank=True, max_length=40, null=True)),
                ('foto_refugio', models.ImageField(upload_to='refugios')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
