# Generated by Django 3.0.4 on 2020-12-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugios', '0002_auto_20201231_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='celular',
            field=models.IntegerField(default=0, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refugio',
            name='codigoArea',
            field=models.IntegerField(default='0', verbose_name='Prefijo'),
            preserve_default=False,
        ),
    ]
