# Generated by Django 3.0.4 on 2020-12-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refugios', '0003_auto_20201231_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refugio',
            old_name='tel',
            new_name='telefono',
        ),
    ]
