# Generated by Django 3.0.4 on 2020-11-06 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('domicilio', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=40)),
                ('cp', models.CharField(max_length=40)),
                ('codigoArea', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('confirmacionEmail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('confirmacionPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMascota', models.CharField(max_length=40)),
                ('raza', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='usuarios')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('provincia', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=40)),
                ('codigoArea', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
