# Generated by Django 3.0.4 on 2020-11-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='categoria',
            field=models.CharField(choices=[('Perro', 'Perro')], default='Perro', max_length=10),
        ),
    ]
