# Generated by Django 3.0.4 on 2021-05-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busqueda',
            name='cp',
            field=models.CharField(max_length=15, verbose_name='Código Postal'),
        ),
    ]
