# Generated by Django 3.0.4 on 2020-11-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_busqueda_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busqueda',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Perro', 'Perro')], max_length=10),
        ),
    ]
