# Generated by Django 3.2 on 2021-05-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210501_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmacionEmail',
            field=models.EmailField(max_length=254, verbose_name='Email (confirmación)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=40, unique=True, verbose_name='Usuario'),
        ),
    ]
