# Generated by Django 3.0.4 on 2020-11-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20201105_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busqueda',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=10),
        ),
    ]
