# Generated by Django 3.0.4 on 2020-11-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20201105_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busqueda',
            name='categoria',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], default='Perro', max_length=10),
        ),
    ]
