# Generated by Django 3.0.4 on 2020-12-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20201201_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='cp',
            field=models.IntegerField(default='0', verbose_name='Código Postal'),
            preserve_default=False,
        ),
    ]
