# Generated by Django 3.0.4 on 2021-05-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('confirmacionEmail', models.EmailField(max_length=254, verbose_name='Confirmación Email')),
                ('codigoArea', models.IntegerField(verbose_name='Código de área')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('domicilio', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=40)),
                ('cp', models.CharField(max_length=40, verbose_name='Código Postal')),
                ('consulta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_newsletter', models.EmailField(max_length=254)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
