# Generated by Django 3.0.4 on 2020-11-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('confirmacionEmail', models.EmailField(max_length=254)),
                ('codigoArea', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('domicilio', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=40)),
                ('cp', models.CharField(max_length=40)),
                ('consulta', models.TextField()),
            ],
        ),
    ]
