# Generated by Django 3.0.4 on 2021-01-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='email_newsletter',
        ),
    ]
